export const LIST_POKEMON = 'LIST_POKEMON';
export const GET_LIST_POKEMON_SUCCESS = 'GET_LIST_POKEMON_SUCCESS';
export const GET_LIST_POKEMON_FAIL = 'GET_LIST_POKEMON_FAIL';

export const FILTER_POKEMON = 'FILTER_POKEMON';
export const FILTER_POKEMON_SUCCESS = 'FILTER_POKEMON_SUCCESS'